### ISSUE TITLE
Merge central_region branch

### ISSUE THREAD

**Issue by DanielWinklehner** [DanielWinklehner/spyral_inflector#9]
Can we do this?

**Comment by pweigel** [comment]
Merging _shouldn't_ break anything, but it's been a while. I can look into it over the weekend.

**Comment by DanielWinklehner** [comment]
Sounds good! Remind me, does the central_region branch also have the GUI part or was that a fork?

**Comment by pweigel** [comment]
GUI is in a private repo at the moment and it just imports the inflector module (may be a bit buggy?). I can probably fold it in as an installation option since there are other requirements.

**Comment by DanielWinklehner** [comment]
If you don't mind. It would be good to make sure no work gets lost...

**Comment by DanielWinklehner** [comment]
How is the merge coming along? :)

**Comment by DanielWinklehner** [comment]
Bump

**Comment by pweigel** [comment]
I've fixed the issues with occ on WSL, but now I'm having issues compiling bempp (not bempp-cl). If I can't fix it in a reasonable amount of time, I'll probably install a linux distro and just start from scratch.

**Comment by DanielWinklehner** [comment]
Are you using Anaconda? Let me know if there is anything I can do to help.

**Comment by pweigel** [comment]
Yup, using anaconda these days. I fixed the issue with bempp, but fenics began to seg fault for no clear reason.

**Comment by DanielWinklehner** [comment]
see #8 maybe? Using the environment.yml in PyPATools should work for Ubuntu and Windows both, using meshio, bempp-cl and pythonocc-core. Apparently, OpenCL will not be supported in WSL until maybe WSL2. I have still not used fenics, so I am not sure I can help with that.
